# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "app distription"
  lane :distribution do
     firebase_app_distribution(
        app: "1:392698229136:android:0a258e65e52b6410354315",
        firebase_cli_token: "1//039mvKjLDE5sECgYIARAAGAMSNwF-L9IrYHcZHP0dQX65pi0Bn2QKblv0dxZVi75IgxGLvK1ACJvuAJwTBG_BbfdeJrbgSEjSebU"
      )
  end

end
